server {
  listen 8080;
  server_name _;
  client_max_body_size 25m;

  location = /_eprom/register {
    proxy_pass http://registration-helper:8787/register;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location = /_eprom/push/public-key {
    proxy_pass http://push-gateway:8790/public-key;
  }

  location = /_eprom/push/subscriptions {
    proxy_pass http://push-gateway:8790/subscriptions;
    proxy_set_header Authorization $http_authorization;
  }

  location / {
    proxy_pass http://synapse:8008;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_buffering off;
  }
}
